/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.AddControl;
import controller.deleteControl;
import controller.updateController;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new GradientPanel(0, 153, 255, 153, 51, 153);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        teacherId = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        Addmission = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        birthday = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Subject");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Birthday");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Admission Date");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contact");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, 20));

        teacherId.setText("   ");
        jPanel2.add(teacherId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 130, -1));
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 180, -1));
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 150, 20));
        jPanel2.add(Addmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 180, -1));
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 150, -1));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 80, -1));
        jPanel2.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 180, -1));
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 150, -1));

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addbutton.setForeground(new java.awt.Color(204, 204, 204));
        addbutton.setText("Submit");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher Id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        jPanel2.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\icons8-teacher-80.png")); // NOI18N
        jLabel2.setText("   ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home obj = new Home();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed
 /*
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
      String TeacherId = teacherId.getText().trim();
    String Name = name.getText().trim();
    String Address = address.getText().trim();
    String Subject = subject.getText().trim();
    String AddmissionDate = Addmission.getText().trim();
    String Age = age.getText().trim();
    String Gender = (String) gender.getSelectedItem();
    String Birthday = birthday.getText().trim();
    String Contact = contact.getText().trim();

    // Check if any field is empty
    if (TeacherId.isEmpty() || Name.isEmpty() || Address.isEmpty() || Subject.isEmpty() || 
        AddmissionDate.isEmpty() || Age.isEmpty() || Gender.isEmpty() || 
        Birthday.isEmpty() || Contact.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all fields");
        return;
    }

    try {
        int id = Integer.parseInt(TeacherId);
        int ag = Integer.parseInt(Age);
        int cntct = Integer.parseInt(Contact);

        // Assuming addControl and studentdetails are properly defined elsewhere
        addControl obj = new addControl();
        obj.studentdetails(id, Name, Address, Subject, AddmissionDate, ag, Gender, Birthday, cntct);

        JOptionPane.showMessageDialog(null, "Teacher details submitted successfully");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid number format in Teacher ID, Age, or Contact fields");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "An error occurred while submitting details: " + e.getMessage());
    } 
*/
     
     
// TODO add your handling code here:
     /*   String TeacherId = teacherId.getText();
        String Name = name.getText();
        String Address = address.getText();
        String Subject = subject.getText();
        String AddmissionDate = Addmission.getText();
        String Age = age.getText();
        String Gender = (String)gender.getSelectedItem();
        String Birthday = birthday.getText();
        String Contact = contact.getText();
        
        if (TeacherId.isEmpty() || Name.isEmpty() || Address.isEmpty() || Subject.isEmpty() || AddmissionDate.isEmpty() || Age.isEmpty() || Gender.isEmpty() || Birthday.isEmpty() || Contact.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill all fields");
    return;
}
        
        try
        {
            int id = Integer.parseInt(TeacherId);
            int ag = Integer.parseInt(Age);
            int cntct = Integer.parseInt(Contact);
            addControl obj = new addControl();
            obj.studentdetails(id,Name,Address,Subject,AddmissionDate,ag,Gender,Birthday,cntct);
            
        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "invalid number format");
    }//GEN-LAST:event_addbuttonActionPerformed
*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idText = teacherId.getText(); 
        String nameText = name.getText();  
        String addrssText = address.getText();
        String ageText = age.getText();
        String contactText = contact.getText();
    
    try {
            int id = Integer.parseInt(idText);           
            int age = Integer.parseInt(ageText);
            int contact = Integer.parseInt(contactText);
            

            updateController controller = new updateController();
            controller.update(id, nameText, addrssText, age,contact );
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String idText = teacherId.getText();
      
       try {
            int id = Integer.parseInt(idText);

            deleteControl controller = new deleteControl();
            controller.delete(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
     
    
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        String TeacherId = teacherId.getText().trim();
        String Name = name.getText().trim();
        String Address = address.getText().trim();
        String Subject = subject.getText().trim();
        String AddmissionDate = Addmission.getText().trim();
        String Age = age.getText().trim();
        String Gender = (String) gender.getSelectedItem();
        String Birthday = birthday.getText().trim();
        String Contact = contact.getText().trim();

        if (TeacherId.isEmpty() || Name.isEmpty() || Address.isEmpty() || Subject.isEmpty() || 
            AddmissionDate.isEmpty() || Age.isEmpty() || Gender.isEmpty() || 
            Birthday.isEmpty() || Contact.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
            return;
        }

        try {
            int id = Integer.parseInt(TeacherId);
            int ag = Integer.parseInt(Age);
            int cntct = Integer.parseInt(Contact);

            AddControl obj = new AddControl();
            obj.studentDetails(id, Name, Address, Subject, AddmissionDate, ag, Gender, Birthday, cntct);

            JOptionPane.showMessageDialog(null, "Teacher details submitted successfully");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid number format in Teacher ID, Age, or Contact fields");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred while submitting details: " + e.getMessage());
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addmission;
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField teacherId;
    // End of variables declaration//GEN-END:variables
}
